language: rust
rust:
  - 1.0.0
  - beta
  - nightly
sudo: false
install:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then OS=unknown-linux-gnu; else OS=apple-darwin; fi
  - export TARGET=$ARCH-$OS
  - if [ "$TRAVIS_RUST_VERSION" = "1.0.0" ]; then PKG=rustc; else PKG=rust-std-$TARGET; fi
  - curl -sO https://static.rust-lang.org/dist/rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - tar xf rust-$TRAVIS_RUST_VERSION-$TARGET.tar.gz
  - rm -rf $HOME/rust/lib/rustlib/$TARGET
  - mv rust-$TRAVIS_RUST_VERSION-$TARGET/$PKG/lib/rustlib/$TARGET $HOME/rust/lib/rustlib
before_script:
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH
script:
  - cargo test --target $TARGET
  - cargo test --release --target $TARGET
  - cargo doc --no-deps
after_success:
  - travis-cargo --only nightly doc-upload
notifications:
  email:
    on_success: never
addons:
  apt:
    packages:
      - gcc-multilib
env:
  global:
    secure: Ud0p1N/8iFQoAKiU/FshXxIawEQc/LdPFOYUnvDAeKW4Eoj0dZES+2hynX6OCZyJi6N4Sd1JgkQM0jEiLj3Go3q550WdmpPkWi6GVm0/DCF00Wo/MimukniUlhXN9XMCEmqOWbYUyxn1ptj1W+0DhjLRpRFkGt3egcEjmGdwVJNwulw4e/hJgJZHaQhNquKQz2d34ti1ZWYD+U3xxIYx/ZlhkCkwm0Gu0G2Po+1KtKGmyTHK5e07UzFHEKFHczId6khNx6WRx6yJsMUrKoatGz21JZ5WVNPjLHVIvEfr2GfzDew7EQfwYP2yd2A0nQkVgZ/miTbicAfObcUUZ4D5Z+d7czYDtB9VaFRqq+f6yn/YSb3W8s8ZH+/BMwhPkbAmZSa+npkZzuuqL+a+8nWEptpzVv6zLfKZtslZOtwZ0kclujuo1y882Y1CMVVCIGnn2Txm1pgya339dVsjm3QztKTMZ/MreO3UrzjfVz511FRtcWuo6V98HdXQb3VHHrYlk+Ou+8X5d3OFqRHE2bshUxJdXqqpVhqi30UI/VeRGHMSxLvpEi7lrTki95uP1+f6+wyE1H0udH8nPSwfnOMzANA+Rkrl+fu6oRMzARtWd1MZ2CF+znQA2fPQYyNA7pPUuaZRNGvOKQBo9kZo8kUFvW2CGChnMjlkvtb7v+UurWs=
  matrix:
    - ARCH=x86_64
    - ARCH=i686

os:
  - linux
  - osx
