language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=wasm32-unknown-unknown
      install: 
        - rustup target add $TARGET
        - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
      script:
        - wasm-pack test --chrome --headless --release wasm-tests
      addons:
        chrome: stable
    - env: TARGET=i686-unknown-linux-gnu
      install: rustup target add $TARGET
      addons:
        apt:
          packages:
            - gcc-multilib
    - env: TARGET=x86_64-apple-darwin
      os: osx
    - env: TARGET=i686-apple-darwin
      os: osx
      install: rustup target add $TARGET
    - rust: beta
      env: TARGET=x86_64-unknown-linux-gnu

    - name: "master doc to gh-pages"
      rust: nightly
      script:
        - cargo doc --no-deps
      deploy:
        provider: script
        script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd target/doc && ../../rust_out)
        skip_cleanup: true
        on:
          branch: master

script:
  - cargo test --target $TARGET
  - cargo test --release --target $TARGET

notifications:
  email:
    on_success: never

branches:
  only:
    - master
