[package]
name = "wasm-tests"
version = "0.1.0"
authors = ["Sergey Shulepov <sergei@parity.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
stacker = { path = ".." }

[dev-dependencies]
wasm-bindgen-test = "0.2"
